apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubecit-service
  namespace: wlb965
spec:
  selector:
    matchLabels:
      app: kubecit-service
  replicas: 1
  template:
    metadata:
      labels:
        app: kubecit-service
    spec:
      volumes:
        - name: kubecit-service-config
          configMap:
            name: kubecit-service-config
      containers:
        - name: kubecit-service
          image: chaoyue/kubecit-service:1695960813-a9e622a #{"$imagepolicy": "flux-system:kubecit-service"}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          volumeMounts:
            - name: kubecit-service-config
              mountPath: /app/configs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubecit-web-service
  namespace: wlb965
spec:
  selector:
    matchLabels:
      app: kubecit-web-service
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: kubecit-web-service
    spec:
      containers:
        - name: kubecit-web-service
          image: chaoyue/kubecit-web:0.0.15
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: kubecit-service
  namespace: wlb965
spec:
  selector:
    app: kubecit-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: kubecit-web-service
  namespace: wlb965
spec:
  selector:
    app: kubecit-web-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
