apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubecit-service
  namespace: wlb965
spec:
  selector:
    matchLabels:
      app: kubecit-service
  replicas: 1
  template:
    metadata:
      labels:
        app: kubecit-service
    spec:
      containers:
        - name: kubecit-service
          image: chaoyue/kubecit-service:v1.0.0 #{"": "flux-system:kubecit-service"}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
